image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Test

integration-test-job:
  stage: Test
  script:
    - echo "Preparing test"
    - python -m pytest --junitxml=report.xml -v -p no:cacheprovider --disable-pytest-warnings
    - echo "Finish"
  artifacts:
    when: always
    reports:
      junit: report.xml


