image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Test


integration-test-job:
  stage: Test
  script:
    - echo "Preparing test"
    - python -m pytest -v -p no:cacheprovider no:warnings
    - echo "Finish"


